AWSTemplateFormatVersion: 2010-09-09
Description: ALB template

Parameters:
  System:
    Type: String
    Default: cicd-handson
  Env:
    Type: String
    Default: test
  VpcId:
    Type: String
    Default: vpc-xxxxxxxxx    
  PublicSubnetA:
    Type: String
    Default: subnet-xxxxxxxxx
  PublicSubnetC:
    Type: String
    Default: subnet-xxxxxxxxx
  SecurityGroup:
    Type: String
    Default: sg-xxxxxxxxx

Resources:
  ALBTargetGroup: 
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      VpcId: !Ref VpcId
      Name: !Sub ${System}-${Env}-alb-tg
      Protocol: HTTP
      Port: 8501 #streamlitコンテナのポート
      TargetType: ip
  
  ALB: 
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      IpAddressType: ipv4
      Name: !Sub ${System}-${Env}-alb
      Type: application
      Scheme: internet-facing
      SecurityGroups:
        - !Ref SecurityGroup
      Subnets: 
        - !Ref PublicSubnetA
        - !Ref PublicSubnetC

  ALBListener: 
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties: 
      DefaultActions: 
        - TargetGroupArn: !Ref ALBTargetGroup
          Type: forward
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP