AWSTemplateFormatVersion: 2010-09-09
Description: client vpn template, acm resources are created manually

Parameters:
  System:
    Type: String
    Default: hoan
  Env:
    Type: String
    Default: test
  VpcId:
    Type: String
    Default: vpc-xxxxxxxxxxxx
  PrivateSubnetVPN01:
    Type: String
    Default: subnet-xxxxxxxxxxxxxx
  ServerCertificate:
    Type: String
    Default: Server Certificate ARN
  ClientCertificate:
    Type: String
    Default: Client Certificate ARN
  VPNSecurityGroup:
    Type: String
    Default: VPNSecurityGroup

Resources:
  EC2NetworkInterface:
    Type: 'AWS::EC2::NetworkInterface'
    Properties:
      SubnetId: !Ref PrivateSubnetVPN01
      GroupSet: 
        - !Ref VPNSecurityGroup

  ClientVpnEndpoint:
    Type: 'AWS::EC2::ClientVpnEndpoint'
    Properties:
      ClientCidrBlock: 192.168.8.0/22 # Can be any value
      ServerCertificateArn: !Ref ServerCertificate
      AuthenticationOptions:
        - Type: certificate-authentication
          MutualAuthentication:
            ClientRootCertificateChainArn: !Ref ClientCertificate
      VpnPort: 443
      VpcId: !Ref VpcId
      SecurityGroupIds: !Ref VPNSecurityGroup
      SplitTunnel: true
      ClientConnectOptions:
        Enabled: false

  ClientVpnTargetNetworkAssociation:
    Type: AWS::EC2::ClientVpnTargetNetworkAssociation
    Properties: 
      ClientVpnEndpointId: !Ref ClientVpnEndpoint
      SubnetId: !Ref PrivateSubnetVPN01