AWSTemplateFormatVersion: 2010-09-09
Description: ECR template

Parameters:
  System:
    Type: String
    Default: cicd-handson
  Env:
    Type: String
    Default: test

Resources:
  ECRRepository:
    Type: 'AWS::ECR::Repository'
    Properties:
      RepositoryName: !Sub ${System}-${Env}-ecr-repository
      EmptyOnDelete: false
      EncryptionConfiguration:
        EncryptionType: KMS
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: IMMUTABLE