name: Deploy CloudFormation Endpoint Stack

on:
  push:
    branches:
      - main
    paths:
      - 'aws/cloudformation/endpoint.yml' 
  pull_request:
    branches:
      - main
    paths:
      - 'aws/cloudformation/endpoint.yml' 

env:
  CFN_TEMPLATE: endpoint.yml
  CFN_STACK_NAME: endpoint-stack
  AWS_REGION: ap-northeast-1

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Configure AWS Credential
      uses: aws-actions/configure-aws-credentials@v4
      with: 
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy CloudFormation stack
      run: |
        aws cloudformation deploy \
          --template-file aws/cloudformation/${{ env.CFN_TEMPLATE }} \
          --stack-name ${{ env.CFN_STACK_NAME }} \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides \
            VpcId=${{ secrets.CFN_VPC_ID }} \
            PrivateSubnetA=${{ secrets.CFN_PRIVATE_SUBNET_A }} \
            PrivateSubnetC=${{ secrets.CFN_PRIVATE_SUBNET_C }} \
            EndpointSecurityGroup=${{ secrets.CFN_Endpoint_SECURITY_GROUP }}
