name: Deploy CloudFormation alb Stack

on:
  push:
    branches:
      - main
    paths:
      - 'aws/cloudformation/alb.yml' 
  pull_request:
    branches:
      - main
    paths:
      - 'aws/cloudformation/alb.yml' 

env:
  CFN_TEMPLATE: alb.yml
  CFN_STACK_NAME: alb-stack
  CFN_SYSTEM: cicd-handson
  CFN_ENV: test  
  CFN_PUBLIC_SUBNET_A: subnet-09d7b4586cf6b18a1
  CFN_PUBLIC_SUBNET_C: subnet-05acda47c5c3ccc65
  CFN_Security_Group: sg-0c5cd20058a03fa92
  AWS_REGION: ap-northeast-1

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Configure AWS Credential
      uses: aws-actions/configure-aws-credentials@v4
      with: 
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy CloudFormation stack
      run: |
        aws cloudformation deploy \
          --template-file aws/cloudformation/${{ env.CFN_TEMPLATE }} \
          --stack-name ${{ env.CFN_STACK_NAME }} \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides \
            System=${{ env.CFN_SYSTEM }} \
            Env=${{ env.CFN_ENV }} \
            VpcId=${{ secrets.CFN_VPC_ID }} \
            PublicSubnetA=${{ env.CFN_PUBLIC_SUBNET_A }} \
            PublicSubnetC=${{ env.CFN_PUBLIC_SUBNET_C }} \
            SecurityGroup=${{ env.CFN_Security_Group }}
